(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> 'str' object has no attribute 'items'"
p3
sS'layer'
p4
S'/home/joseph/BabbleBot/applications/BabbleBot/controllers/features.py'
p5
sS'code'
p6
S'<code object <module> at 0x7ff9bc73ae30, file "/home/joseph/BabbleBot/applications/BabbleBot/controllers/features.py", line 2>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/joseph/BabbleBot/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/joseph/BabbleBot/applications/BabbleBot/controllers/features.py", line 47, in <module>\n  File "/home/joseph/BabbleBot/gluon/globals.py", line 419, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/joseph/BabbleBot/applications/BabbleBot/controllers/features.py", line 44, in mostGivingUsers\n    sortedUserDict = dict(sorted(userDict.items(), key=lambda x: x[0])) # put it all back into a dict\nAttributeError: \'str\' object has no attribute \'items\'\n'
p11
s.