(dp1
S'output'
p2
S"<type 'exceptions.TypeError'> 'NoneType' object has no attribute '__getitem__'"
p3
sS'layer'
p4
S'/home/joseph/BabbleBot/applications/BabbleBot/controllers/userFeatures.py'
p5
sS'code'
p6
S'<code object <module> at 0x7f92e174dcb0, file "/home/joseph/BabbleBot/applications/BabbleBot/controllers/userFeatures.py", line 2>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/joseph/BabbleBot/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/joseph/BabbleBot/applications/BabbleBot/controllers/userFeatures.py", line 16, in <module>\n  File "/home/joseph/BabbleBot/gluon/globals.py", line 419, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/joseph/BabbleBot/applications/BabbleBot/controllers/userFeatures.py", line 8, in main\n    name = session.translator[personID]\nTypeError: \'NoneType\' object has no attribute \'__getitem__\'\n'
p11
s.